name: 'BRD LLC. '
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: "Micro Molding at it's Smallest"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c3c3c'
    - '#0d0d0d'
    - '#ff2929'
    - '#989898'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
